contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnaseqtranscriptomeupdate channel"
    url: https://nfcore.slack.com/channels/rnaseqtranscriptomeupdate
    about: Discussion about the nf-core/rnaseqtranscriptomeupdate pipeline
