name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/rnaseq') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Hash Github Workspace
        id: hash_workspace
        run: |
          echo "digest=$(echo RNA_3.10.1_${{ github.workspace }} | md5sum | cut -c 1-25)" >> $GITHUB_OUTPUT

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: test-datasets/
          key: ${{ steps.hash_workspace.outputs.digest }}

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: rnaseq3
          path: test-datasets/

      - name: Replace remote paths in samplesheets
        run: |
          for f in ${{ github.workspace }}/test-datasets/samplesheet/v3.10/*.csv; do
            sed -i "s=https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/=${{ github.workspace }}/test-datasets/=g" $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_cache,docker --outdir ./results --test_data_base ${{ github.workspace }}/test-datasets/

  star_salmon:
    name: Test STAR Salmon with workflow parameters
    if: ${{ (github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/rnaseq')) && !contains(github.event.head_commit.message, '[ci fast]') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
          - "--skip_qc"
          - "--skip_trimming"
          - "--gtf false"
          - "--star_index false"
          - "--transcript_fasta false"
          - "--min_mapped_reads 90"
          - "--with_umi"
          - "--with_umi --skip_trimming"
          - "--remove_ribo_rna --skip_qualimap"
          - "--bam_csi_index"
          - "--save_align_intermeds --save_reference"
          - "--featurecounts_group_type false"
          - "--trimmer fastp"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Hash Github Workspace
        id: hash_workspace
        run: |
          echo "digest=$(echo RNA_3.10.1_${{ github.workspace }} | md5sum | cut -c 1-25)" >> $GITHUB_OUTPUT

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: test-datasets/
          key: ${{ steps.hash_workspace.outputs.digest }}

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: rnaseq3
          path: test-datasets/

      - name: Replace remote paths in samplesheets
        run: |
          for f in ${{ github.workspace }}/test-datasets/samplesheet/v3.10/*.csv; do
            sed -i "s=https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/=${{ github.workspace }}/test-datasets/=g" $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with STAR and various parameters
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_cache,docker --aligner star_salmon ${{ matrix.parameters }} --outdir ./results --test_data_base ${{ github.workspace }}/test-datasets/

  star_rsem:
    name: Test STAR RSEM with workflow parameters
    if: ${{ (github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/rnaseq')) && !contains(github.event.head_commit.message, '[ci fast]') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
          - "--skip_qc"
          - "--rsem_index false"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Hash Github Workspace
        id: hash_workspace
        run: |
          echo "digest=$(echo RNA_3.10.1_${{ github.workspace }} | md5sum | cut -c 1-25)" >> $GITHUB_OUTPUT

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: test-datasets/
          key: ${{ steps.hash_workspace.outputs.digest }}

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: rnaseq3
          path: test-datasets/

      - name: Replace remote paths in samplesheets
        run: |
          for f in ${{ github.workspace }}/test-datasets/samplesheet/v3.10/*.csv; do
            sed -i "s=https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/=${{ github.workspace }}/test-datasets/=g" $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with RSEM STAR and various parameters
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_cache,docker --aligner star_rsem ${{ matrix.parameters }} --outdir ./results --test_data_base ${{ github.workspace }}/test-datasets/

  hisat2:
    name: Test HISAT2 with workflow parameters
    if: ${{ (github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/rnaseq')) && !contains(github.event.head_commit.message, '[ci fast]') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
          - "--skip_qc"
          - "--hisat2_index false"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Hash Github Workspace
        id: hash_workspace
        run: |
          echo "digest=$(echo RNA_3.10.1_${{ github.workspace }} | md5sum | cut -c 1-25)" >> $GITHUB_OUTPUT

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: test-datasets/
          key: ${{ steps.hash_workspace.outputs.digest }}

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: rnaseq3
          path: test-datasets/

      - name: Replace remote paths in samplesheets
        run: |
          for f in ${{ github.workspace }}/test-datasets/samplesheet/v3.10/*.csv; do
            sed -i "s=https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/=${{ github.workspace }}/test-datasets/=g" $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with HISAT2 and various parameters
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_cache,docker --aligner hisat2 ${{ matrix.parameters }} --outdir ./results --test_data_base ${{ github.workspace }}/test-datasets/

  pseudo:
    name: Test Pseudoaligners with workflow parameters
    if: ${{ (github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/rnaseq')) && !contains(github.event.head_commit.message, '[ci fast]') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
          - "--pseudo_aligner salmon --skip_qc"
          - "--pseudo_aligner salmon --skip_alignment --skip_pseudo_alignment"
          - "--pseudo_aligner salmon --salmon_index false --transcript_fasta false"
          - "--pseudo_aligner kallisto --skip_qc"
          - "--pseudo_aligner kallisto --skip_alignment --skip_pseudo_alignment"
          - "--pseudo_aligner kallisto --kallisto_index false --transcript_fasta false"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Hash Github Workspace
        id: hash_workspace
        run: |
          echo "digest=$(echo RNA_3.10.1_${{ github.workspace }} | md5sum | cut -c 1-25)" >> $GITHUB_OUTPUT

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: test-datasets/
          key: ${{ steps.hash_workspace.outputs.digest }}

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: rnaseq3
          path: test-datasets/

      - name: Replace remote paths in samplesheets
        run: |
          for f in ${{ github.workspace }}/test-datasets/samplesheet/v3.10/*.csv; do
            sed -i "s=https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/=${{ github.workspace }}/test-datasets/=g" $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with Salmon or Kallisto and various parameters
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_cache,docker ${{ matrix.parameters }} --outdir ./results --test_data_base ${{ github.workspace }}/test-datasets/
